name : SRE Automation Project

on: 
  push:
    branches: [main, feature/*]
  workflow_dispatch:

jobs: 
  run_health_check:
    runs_on: ubuntu@latest

  steps:
    - name: Grab my code
      uses: action/checkout@v4
    
    - name: Setup Python
      uses: actions/setup@python@v5
      with: 
        python-version: '3.10'

    - name: Install Tools
      run: pip install requests 

    - name: Run the Script
      run: pyhton check_site.py
